"""Constants for Recommendation Engine scoring, ranking, and execution."""

DEFAULT_TOP_K = 5
MAX_TOP_K = 10
MAX_CANDIDATES = 50
MIN_CONFIDENCE = 0.40
MIN_RECOMMENDATION_SCORE = 50
MIN_NEWS_SIMILARITY = 0.50
MAX_EXPLANATION_STOCKS = 5
RECOMMENDATION_VERSION = "v1"
DEFAULT_RECOMMENDATION_MODEL = "gemini-flash-latest"

# Weighted Scoring Engine Component Weights (Sum = 1.0)
FUNDAMENTALS_WEIGHT = 0.35
NEWS_WEIGHT = 0.25
MEMORY_WEIGHT = 0.20
PORTFOLIO_WEIGHT = 0.10
TREND_WEIGHT = 0.10
