from typing import Any
from pydantic import BaseModel, Field


class RecommendationRequest(BaseModel):
    """Input payload for POST /api/recommendations API request."""
    top_k: int = Field(default=5, description="Number of top recommendation results (max 10)")
    sector: str | None = Field(default=None, description="Optional target sector filter")
    risk_override: str | None = Field(default=None, description="Optional risk profile override (Conservative|Moderate|Aggressive)")
    investment_style: str | None = Field(default=None, description="Optional style filter (Growth|Value|Dividend)")
    investment_horizon: str | None = Field(default=None, description="Optional horizon filter (Short Term|Long Term)")
    include_watchlist: bool = Field(default=True, description="Whether to incorporate user watchlist status")


class RecommendationReasonSchema(BaseModel):
    """Schema for individual recommendation reason."""
    title: str
    description: str
    category: str


class RecommendationItemSchema(BaseModel):
    """Schema for a single recommended stock item."""
    company_name: str
    ticker: str
    exchange: str
    overall_score: float
    confidence: float
    fundamental_score: float
    news_score: float
    memory_score: float
    portfolio_score: float
    trend_score: float
    reasons: list[RecommendationReasonSchema] = Field(default_factory=list)
    risk_level: str
    expected_horizon: str


class RecommendationResponse(BaseModel):
    """Output response payload for POST /api/recommendations API request."""
    explanation: str = Field(..., description="Grounded natural language explanation generated by Gemini LLM")
    recommendations: list[RecommendationItemSchema] = Field(default_factory=list)
    total_candidates: int
    execution_time_ms: float
    confidence: float = Field(default=0.85)
    citations: list[dict[str, Any]] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)
