"""link document_embeddings to document_chunks

Revision ID: 03e3f8259f99
Revises: 36e8168a32f1
Create Date: 2026-08-01 12:09:34.135505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '03e3f8259f99'
down_revision: Union[str, Sequence[str], None] = '36e8168a32f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_embeddings', sa.Column('chunk_id', sa.UUID(), nullable=False))
    op.add_column('document_embeddings', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('document_embeddings', sa.Column('dimensions', sa.Integer(), nullable=False))
    op.alter_column('document_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               nullable=False)
    op.drop_index(op.f('ix_document_embeddings_document_id'), table_name='document_embeddings')
    op.create_index(op.f('ix_document_embeddings_chunk_id'), 'document_embeddings', ['chunk_id'], unique=True)
    op.create_unique_constraint('uq_document_embeddings_chunk_id', 'document_embeddings', ['chunk_id'])
    op.drop_constraint(op.f('document_embeddings_document_id_fkey'), 'document_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'document_embeddings', 'document_chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    op.drop_column('document_embeddings', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_embeddings', sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('document_embeddings_document_id_fkey'), 'document_embeddings', 'knowledge_documents', ['document_id'], ['id'])
    op.drop_constraint('uq_document_embeddings_chunk_id', 'document_embeddings', type_='unique')
    op.drop_index(op.f('ix_document_embeddings_chunk_id'), table_name='document_embeddings')
    op.create_index(op.f('ix_document_embeddings_document_id'), 'document_embeddings', ['document_id'], unique=False)
    op.alter_column('document_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               nullable=True)
    op.drop_column('document_embeddings', 'dimensions')
    op.drop_column('document_embeddings', 'provider')
    op.drop_column('document_embeddings', 'chunk_id')
    # ### end Alembic commands ###
