"""extend company master schema

Revision ID: 4273ce2ebe69
Revises: 6ef86af4cef4
Create Date: 2026-08-01 10:24:11.821766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4273ce2ebe69'
down_revision: Union[str, Sequence[str], None] = '6ef86af4cef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('nse_symbol', sa.String(length=30), nullable=True))
    op.add_column('companies', sa.Column('bse_symbol', sa.String(length=30), nullable=True))
    op.add_column('companies', sa.Column('isin', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_companies_isin'), 'companies', ['isin'], unique=True)
    op.create_unique_constraint(None, 'companies', ['nse_symbol'])
    op.create_unique_constraint(None, 'companies', ['bse_symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_index(op.f('ix_companies_isin'), table_name='companies')
    op.drop_column('companies', 'is_active')
    op.drop_column('companies', 'isin')
    op.drop_column('companies', 'bse_symbol')
    op.drop_column('companies', 'nse_symbol')
    # ### end Alembic commands ###
