"""extend knowledge document schema

Revision ID: 6dbf61ed13f2
Revises: b747f1d4848d
Create Date: 2026-08-01 11:25:06.705434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbf61ed13f2'
down_revision: Union[str, Sequence[str], None] = 'b747f1d4848d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('knowledge_documents', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('knowledge_documents', sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_knowledge_documents_content_hash'), 'knowledge_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_source_url'), 'knowledge_documents', ['source_url'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_source_url'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_content_hash'), table_name='knowledge_documents')
    op.drop_column('knowledge_documents', 'ingested_at')
    op.drop_column('knowledge_documents', 'status')
    op.drop_column('knowledge_documents', 'content_hash')
    # ### end Alembic commands ###
