"""add_chat_conversations_and_messages

Revision ID: 7824a8ece51e
Revises: 03e3f8259f99
Create Date: 2026-08-01 13:04:15.637065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7824a8ece51e'
down_revision: Union[str, Sequence[str], None] = '03e3f8259f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_is_deleted'), 'chat_conversations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chat_conversations_user_id'), 'chat_conversations', ['user_id'], unique=False)
    
    # Drop existing foreign key and indices before dropping chat_sessions table
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    
    op.add_column('chat_messages', sa.Column('conversation_id', sa.UUID(), nullable=False))
    op.add_column('chat_messages', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'chat_conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'updated_at')
    op.drop_column('chat_messages', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.drop_column('chat_messages', 'completion_tokens')
    op.drop_column('chat_messages', 'prompt_tokens')
    op.drop_column('chat_messages', 'token_count')
    op.drop_column('chat_messages', 'conversation_id')
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_sessions_pkey'))
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_chat_conversations_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_is_deleted'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
