"""extend company fundamentals schema

Revision ID: b747f1d4848d
Revises: 4273ce2ebe69
Create Date: 2026-08-01 10:58:06.494354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b747f1d4848d'
down_revision: Union[str, Sequence[str], None] = '4273ce2ebe69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_fundamentals', sa.Column('current_price', sa.DECIMAL(precision=12, scale=4), nullable=True))
    op.add_column('company_fundamentals', sa.Column('shares_outstanding', sa.BigInteger(), nullable=True))
    op.add_column('company_fundamentals', sa.Column('price_to_book', sa.DECIMAL(precision=12, scale=4), nullable=True))
    op.add_column('company_fundamentals', sa.Column('beta', sa.DECIMAL(precision=12, scale=4), nullable=True))
    op.add_column('company_fundamentals', sa.Column('fifty_two_week_high', sa.DECIMAL(precision=12, scale=4), nullable=True))
    op.add_column('company_fundamentals', sa.Column('fifty_two_week_low', sa.DECIMAL(precision=12, scale=4), nullable=True))
    op.add_column('company_fundamentals', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('company_fundamentals', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('company_fundamentals', 'pe_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('company_fundamentals', 'eps',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('company_fundamentals', 'roe',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('company_fundamentals', 'debt_to_equity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('company_fundamentals', 'dividend_yield',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('company_fundamentals', 'book_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=12, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_fundamentals', 'book_value',
               existing_type=sa.DECIMAL(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('company_fundamentals', 'dividend_yield',
               existing_type=sa.DECIMAL(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('company_fundamentals', 'debt_to_equity',
               existing_type=sa.DECIMAL(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('company_fundamentals', 'roe',
               existing_type=sa.DECIMAL(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('company_fundamentals', 'eps',
               existing_type=sa.DECIMAL(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('company_fundamentals', 'pe_ratio',
               existing_type=sa.DECIMAL(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('company_fundamentals', 'last_updated')
    op.drop_column('company_fundamentals', 'currency')
    op.drop_column('company_fundamentals', 'fifty_two_week_low')
    op.drop_column('company_fundamentals', 'fifty_two_week_high')
    op.drop_column('company_fundamentals', 'beta')
    op.drop_column('company_fundamentals', 'price_to_book')
    op.drop_column('company_fundamentals', 'shares_outstanding')
    op.drop_column('company_fundamentals', 'current_price')
    # ### end Alembic commands ###
