"""Constants for document text chunking configuration and status lifecycle."""

DEFAULT_CHUNK_SIZE = 700
DEFAULT_CHUNK_OVERLAP = 100

CHUNK_STATUS_NEW = "NEW"
CHUNK_STATUS_EMBEDDING_PENDING = "EMBEDDING_PENDING"
CHUNK_STATUS_EMBEDDED = "EMBEDDED"
CHUNK_STATUS_FAILED = "FAILED"
